_target_: pytorch_lightning.Trainer

max_epochs: 2
precision: 16-mixed
accelerator: cpu
devices: auto
callbacks:
  - _target_: pytorch_lightning.callbacks.RichProgressBar
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 5
    monitor: Epoch_val_loss
    mode: min
    save_last: true
    dirpath: ${root_dir}/checkpoints
    filename: ${model_name} + "-{epoch:02d}-{val_loss:.2f}"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ${root_dir}/lightning_logs
  project: VAE_Training
